targets = [ "//:get" ]

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
version = "*"

[[dependency]]
package = "github.com/buckaroo-pm/mapbox-rapidjson"
version = "*"

[[dependency]]
package = "github.com/buckaroo-pm/nmoinvaz-minizip"
version = "1.1.0"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-curl"
version = "*"

